# Generated by Django 4.2.4 on 2024-07-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='gpa',
            new_name='cgpa',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='field_of_study',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='tyl_eligibility',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_number',
        ),
        migrations.AddField(
            model_name='student',
            name='usn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
