# Generated by Django 4.2.4 on 2024-07-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_gpa_student_cgpa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='usn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
